### ISSUE TITLE
sublime text 3 package Gnuplot doe not display graph

### ISSUE THREAD

**Issue by Compa0** [hesstobi/sublime_gnuplot#4]
I am using GNUplot 5.0 and Sublime text 3 on Windows 10. I found your package "GNUplot" for sublime text 3, which could build gnuplot script from sublime text 3.

But when I build it, all the graph is not displayed, while other command works fine:
http://i.stack.imgur.com/35S8m.png

Also, the Task Manager shows as many "gnuplot.exe' as the times I build, which does not automatically shut down： http://i.stack.imgur.com/lrPm0.png

I tried to use the GNUplot program directly, and it works fine without any problem.

So, it seems there are problems with the package. But there is no settings for it in sublime text. How could I fix it?

I tried the command "pause -1", which does not work, either: i.stack.imgur.com/muHc4.png

**Comment by Kristinita** [comment]
I fully reproduce this problem in Windows 10 64-bit.

`sublime-build` file it seems to be valid. Perhaps, the problem in gnuplot or Sublime Text core, but not sublime_gnuplot.

See [**my bugreport**](https://sourceforge.net/p/gnuplot/bugs/1910/).

Thanks.
